trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VAR_admin_password: $(admin_password)

container:
  image: yourdockerhubusername/terraform-azure:latest  # Replace with your Docker image

steps:
  - script: |
      az --version
      terraform version
    displayName: 'Verify Azure CLI and Terraform Installation'

  - script: |
      az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    displayName: 'Azure CLI Login'

  - script: |
      terraform init
      terraform validate
      terraform plan -out=tfplan
    displayName: 'Terraform Init, Validate, and Plan'
    env:
      ARM_SUBSCRIPTION_ID: $(subscriptionId)

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
    env:
      ARM_SUBSCRIPTION_ID: $(subscriptionId)
